cmake_minimum_required(VERSION 3.25)

foreach(required_variable IN ITEMS NATIVE_EXECUTABLE INPUT_FILE TEST_CASE)
  if(NOT DEFINED ${required_variable})
    message(FATAL_ERROR "${required_variable} is required")
  endif()
endforeach()

set(expect_success TRUE)
if(TEST_CASE STREQUAL "exact")
  set(arguments exact)
  set(expected_mode exact)
elseif(TEST_CASE STREQUAL "compact")
  set(arguments compact)
  set(expected_mode compact)
elseif(TEST_CASE STREQUAL "equals_exact")
  set(arguments --mode=exact)
  set(expected_mode exact)
elseif(TEST_CASE STREQUAL "equals_compact")
  set(arguments --mode=compact)
  set(expected_mode compact)
elseif(TEST_CASE STREQUAL "split_exact")
  set(arguments --mode exact)
  set(expected_mode exact)
elseif(TEST_CASE STREQUAL "split_compact")
  set(arguments --mode compact)
  set(expected_mode compact)
elseif(TEST_CASE STREQUAL "invalid_usage")
  set(arguments invalid)
  set(expect_success FALSE)
else()
  message(FATAL_ERROR "Unknown TEST_CASE=${TEST_CASE}")
endif()

execute_process(
  COMMAND "${NATIVE_EXECUTABLE}" ${arguments}
  INPUT_FILE "${INPUT_FILE}"
  OUTPUT_VARIABLE output
  ERROR_VARIABLE error
  RESULT_VARIABLE result
)

if(expect_success)
  if(NOT result EQUAL 0)
    message(FATAL_ERROR "Expected exit 0, received ${result}: ${error}")
  endif()
  if(NOT error STREQUAL "")
    message(FATAL_ERROR "Successful invocation wrote stderr: ${error}")
  endif()
  if(NOT output MATCHES "\"kind\":\"config\",\"mode\":\"${expected_mode}\"")
    message(FATAL_ERROR "Config record did not report mode=${expected_mode}: ${output}")
  endif()
  if(NOT output MATCHES "\"kind\":\"final\"")
    message(FATAL_ERROR "Successful invocation omitted its final record: ${output}")
  endif()
else()
  if(NOT result EQUAL 2)
    message(FATAL_ERROR "Invalid usage expected exit 2, received ${result}")
  endif()
  if(NOT output STREQUAL "")
    message(FATAL_ERROR "Invalid usage wrote stdout: ${output}")
  endif()
  if(NOT error MATCHES "^usage: atlas_diff_native")
    message(FATAL_ERROR "Invalid usage omitted its diagnostic: ${error}")
  endif()
endif()
