"""Private pybind11 ABI for :mod:`atlaslob.engine`."""

from __future__ import annotations

BINDING_ABI: int
SEMANTICS_VERSION: int

class NativePersistenceError(RuntimeError): ...
class NativeRecoveryError(RuntimeError): ...
class NativeSnapshotError(RuntimeError): ...
class NativeReadOnlyError(RuntimeError): ...

class NativeEngine:
    @property
    def logged(self) -> bool: ...
    @property
    def read_only(self) -> bool: ...
    @property
    def poisoned(self) -> bool: ...
    @property
    def recovery_report(self) -> dict[str, object] | None: ...
    def __init__(
        self,
        catalog: list[dict[str, object]],
        max_total_active_orders: int,
    ) -> None: ...
    @classmethod
    def create_logged(
        cls,
        path: str,
        catalog: list[dict[str, object]],
        max_total_active_orders: int,
        durability: str = ...,
    ) -> NativeEngine: ...
    @classmethod
    def recover(
        cls,
        log_path: str,
        snapshot_path: str | None = ...,
        snapshot_dir: str | None = ...,
        mode: str = ...,
        tail_policy: str = ...,
        durability: str = ...,
    ) -> NativeEngine: ...
    def submit(self, command: dict[str, object]) -> dict[str, object]: ...
    def submit_batch(
        self,
        commands: list[dict[str, object]],
        output: str = ...,
    ) -> dict[str, object]: ...
    def _submit_batch_for_measurement(
        self,
        commands: list[dict[str, object]],
        output: str = ...,
    ) -> dict[str, object]: ...
    def top(self, instrument_id: int) -> dict[str, object] | None: ...
    def snapshot(self, instrument_id: int | None = ...) -> dict[str, object] | None: ...
    def state_digest(self) -> str: ...
    def write_snapshot(self, directory: str) -> dict[str, object]: ...
